# Setup
title:               Gyu-Ho Lee
tagline:             'A problem solving history'
description:         'Robot Platform and Data analysis engineer<br> Korea Telecom <br>M.Eng of Engineering Practice, SNU'
url:                 https://secondwind86.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Gyuho Lee
  url:               https://twitter.com/mdo
  email:             secondwind86@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.11
google_analytics_id: #UA-XXXX-Y

# categories setting
category_dir: category/
tag_dir: tag/
